import { Content } from "./types";

export const contents: Content[] = [
  {
    id: "kr-jp-grammar",
    title: "한국어와 일본어의 문법 유사성",
    source: "예제 문장",
    full_translation:
      "한국어와 일본어는 문법의 구조가 매우 닮아 있기 때문에, 서로의 말을 직관적으로 이해할 수 있습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "韓国語と",
        reading: "칸코쿠고토",
        definition: "한국어와",
        pos: "명사+조사",
        meta: { word: "韓国語", particle: "と", readingRoot: "칸코쿠고" },
      },
      {
        token_id: 2,
        surface: "日本語は",
        reading: "니혼고와",
        definition: "일본어는",
        pos: "명사+조사",
        meta: { word: "日本語", particle: "は", readingRoot: "니혼고" },
      },
      {
        token_id: 3,
        surface: "文法の",
        reading: "분포오노",
        definition: "문법의",
        pos: "명사+조사",
        meta: { word: "文法", particle: "の", readingRoot: "분포오" },
      },
      {
        token_id: 4,
        surface: "構造が",
        reading: "코오조오가",
        definition: "구조가",
        pos: "명사+조사",
        meta: { word: "構造", particle: "が", readingRoot: "코오조오" },
      },
      {
        token_id: 5,
        surface: "非常に",
        reading: "히죠오니",
        definition: "매우",
        pos: "부사(형용동사 어간+に)",
        meta: { word: "非常", particle: "に", readingRoot: "히죠오" },
      },
      {
        token_id: 6,
        surface: "似ているため、",
        reading: "니테이루타메,",
        definition: "닮아 있기 때문에,",
        pos: "동사(연용형)+접속조사",
        meta: { word: "似ている", particle: "ため", readingRoot: "니테이루" },
      },
      {
        token_id: 7,
        surface: "お互いの",
        reading: "오타가이노",
        definition: "서로의",
        pos: "명사+조사",
        meta: { word: "お互い", particle: "の", readingRoot: "오타가이" },
      },
      {
        token_id: 8,
        surface: "言葉を",
        reading: "코토바오",
        definition: "말을",
        pos: "명사+조사",
        meta: { word: "言葉", particle: "を", readingRoot: "코토바" },
      },
      {
        token_id: 9,
        surface: "直感的に",
        reading: "춋칸테키니",
        definition: "직관적으로",
        pos: "부사(형용동사 어간+に)",
        meta: { word: "直感的", particle: "に", readingRoot: "춋칸테키" },
      },
      {
        token_id: 10,
        surface: "理解することが",
        reading: "리카이스루코토가",
        definition: "이해하는 것이",
        pos: "동사+형식명사+조사",
        meta: {
          word: "理解する",
          particle: "こと+が",
          readingRoot: "리카이스루",
        },
      },
      {
        token_id: 11,
        surface: "できます。",
        reading: "데키마스.",
        definition: "가능합니다.",
        pos: "동사(가능형)",
        meta: { word: "できる", root: "でき", readingRoot: "데키" },
      },
    ],
  },
  {
    id: "yen-travel-news",
    title: "엔저와 관광객 증가",
    source: "NHK Easy News 스타일 예문",
    full_translation:
      "엔저의 영향으로 일본을 방문하는 한국인 관광객이 늘고 있기 때문에, 현지에서는 면세점의 매출도 늘고 있습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "円安の",
        reading: "엔야스노",
        definition: "엔저의",
        pos: "명사+조사",
        meta: { word: "円安", particle: "の", readingRoot: "엔야스" },
      },
      {
        token_id: 2,
        surface: "影響で",
        reading: "에이쿄오데",
        definition: "영향으로",
        pos: "명사+조사",
        meta: { word: "影響", particle: "で", readingRoot: "에이쿄오" },
      },
      {
        token_id: 3,
        surface: "日本を",
        reading: "니혼오",
        definition: "일본을",
        pos: "명사+조사",
        meta: { word: "日本", particle: "を", readingRoot: "니혼" },
      },
      {
        token_id: 4,
        surface: "訪れる",
        reading: "오토즈레루",
        definition: "방문하는",
        pos: "동사(연체형)",
        meta: { word: "訪れる", readingRoot: "오토즈레루" },
      },
      {
        token_id: 5,
        surface: "韓国人観光客が",
        reading: "캉코쿠진캉코오캬쿠가",
        definition: "한국인 관광객이",
        pos: "명사+조사",
        meta: {
          word: "韓国人観光客",
          particle: "が",
          readingRoot: "캉코쿠진캉코오캬쿠",
        },
      },
      {
        token_id: 6,
        surface: "増えているため、",
        reading: "후에테이루타메,",
        definition: "늘고 있기 때문에,",
        pos: "동사(연용형)+접속조사",
        meta: {
          word: "増えている",
          particle: "ため",
          readingRoot: "후에테이루",
        },
      },
      {
        token_id: 7,
        surface: "現地では",
        reading: "겐치데와",
        definition: "현지에서는",
        pos: "명사+조사",
        meta: { word: "現地", particle: "では", readingRoot: "겐치" },
      },
      {
        token_id: 8,
        surface: "免税店の",
        reading: "멘제이텐노",
        definition: "면세점의",
        pos: "명사+조사",
        meta: { word: "免税店", particle: "の", readingRoot: "멘제이텐" },
      },
      {
        token_id: 9,
        surface: "売り上げも",
        reading: "우리아게모",
        definition: "매출도",
        pos: "명사+조사",
        meta: { word: "売り上げ", particle: "も", readingRoot: "우리아게" },
      },
      {
        token_id: 10,
        surface: "伸びています。",
        reading: "노비테이마스.",
        definition: "늘고 있습니다.",
        pos: "동사(현재진행형)",
        meta: { word: "伸びる", root: "伸び", readingRoot: "노비" },
      },
    ],
  },
  {
    id: "old-village-tale",
    title: "어느 마을의 이야기",
    source: "아오조라 문고 스타일 전래동화 예문",
    full_translation:
      "옛날 옛적, 어느 마을에 마음씨 착한 할아버지와 할머니가, 두 아이들과 사이좋게 살고 있었습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "昔々、",
        reading: "무카시무카시,",
        definition: "옛날 옛적,",
        pos: "부사",
        meta: { word: "昔々", readingRoot: "무카시무카시" },
      },
      {
        token_id: 2,
        surface: "ある",
        reading: "아루",
        definition: "어느",
        pos: "연체사",
        meta: { word: "ある", readingRoot: "아루" },
      },
      {
        token_id: 3,
        surface: "村に",
        reading: "무라니",
        definition: "마을에",
        pos: "명사+조사",
        meta: { word: "村", particle: "に", readingRoot: "무라" },
      },
      {
        token_id: 4,
        surface: "心優しい",
        reading: "코코로야사시이",
        definition: "마음씨 착한",
        pos: "형용사(연체형)",
        meta: { word: "心優しい", readingRoot: "코코로야사시이" },
      },
      {
        token_id: 5,
        surface: "おじいさんと",
        reading: "오지이상토",
        definition: "할아버지와",
        pos: "명사+조사",
        meta: { word: "おじいさん", particle: "と", readingRoot: "오지이상" },
      },
      {
        token_id: 6,
        surface: "おばあさんが、",
        reading: "오바아상가,",
        definition: "할머니가,",
        pos: "명사+조사",
        meta: { word: "おばあさん", particle: "が", readingRoot: "오바아상" },
      },
      {
        token_id: 7,
        surface: "二人の",
        reading: "후타리노",
        definition: "두 명의",
        pos: "명사+조사",
        meta: { word: "二人", particle: "の", readingRoot: "후타리" },
      },
      {
        token_id: 8,
        surface: "子どもたちと",
        reading: "코도모타치토",
        definition: "아이들과",
        pos: "명사+조사",
        meta: { word: "子どもたち", particle: "と", readingRoot: "코도모타치" },
      },
      {
        token_id: 9,
        surface: "仲良く",
        reading: "나카요쿠",
        definition: "사이좋게",
        pos: "부사(형용사 연용형)",
        meta: { word: "仲良い", root: "仲良", readingRoot: "나카요" },
      },
      {
        token_id: 10,
        surface: "暮らしていました。",
        reading: "쿠라시테이마시타.",
        definition: "살고 있었습니다.",
        pos: "동사(과거진행형)",
        meta: { word: "暮らす", root: "暮らし", readingRoot: "쿠라시" },
      },
    ],
  },
  {
    id: "daily-study-habit",
    title: "매일 아침 일본어 공부 습관",
    source: "일상 학습 습관 예문",
    full_translation:
      "저는 매일 아침, 전철 안에서 스마트폰을 사용해서 일본어 뉴스를 읽는 연습을 하고 있습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "わたしは",
        reading: "와타시와",
        definition: "저는",
        pos: "명사+조사",
        meta: { word: "わたし", particle: "は", readingRoot: "와타시" },
      },
      {
        token_id: 2,
        surface: "毎朝、",
        reading: "마이아사,",
        definition: "매일 아침,",
        pos: "명사",
        meta: { word: "毎朝", readingRoot: "마이아사" },
      },
      {
        token_id: 3,
        surface: "電車の",
        reading: "덴샤노",
        definition: "전철의",
        pos: "명사+조사",
        meta: { word: "電車", particle: "の", readingRoot: "덴샤" },
      },
      {
        token_id: 4,
        surface: "中で",
        reading: "나카데",
        definition: "안에서",
        pos: "명사+조사",
        meta: { word: "中", particle: "で", readingRoot: "나카" },
      },
      {
        token_id: 5,
        surface: "スマホを",
        reading: "스마호오",
        definition: "스마트폰을",
        pos: "명사+조사",
        meta: { word: "スマホ", particle: "を", readingRoot: "스마호" },
      },
      {
        token_id: 6,
        surface: "使って",
        reading: "츠캇테",
        definition: "사용해서",
        pos: "동사(연용형)",
        meta: { word: "使う", root: "使", readingRoot: "츠캇" },
      },
      {
        token_id: 7,
        surface: "日本語の",
        reading: "니혼고노",
        definition: "일본어",
        pos: "명사+조사",
        meta: { word: "日本語", particle: "の", readingRoot: "니혼고" },
      },
      {
        token_id: 8,
        surface: "ニュースを",
        reading: "뉴우스오",
        definition: "뉴스를",
        pos: "명사+조사",
        meta: { word: "ニュース", particle: "を", readingRoot: "뉴우스" },
      },
      {
        token_id: 9,
        surface: "読む",
        reading: "요무",
        definition: "읽는",
        pos: "동사(연체형)",
        meta: { word: "読む", readingRoot: "요무" },
      },
      {
        token_id: 10,
        surface: "練習を",
        reading: "렌슈우오",
        definition: "연습을",
        pos: "명사+조사",
        meta: { word: "練習", particle: "を", readingRoot: "렌슈우" },
      },
      {
        token_id: 11,
        surface: "しています。",
        reading: "시테이마스.",
        definition: "하고 있습니다.",
        pos: "동사(현재진행형)",
        meta: { word: "する", root: "し", readingRoot: "시" },
      },
    ],
  },
  {
    id: "anime-culture-trend",
    title: "일본 애니메이션과 자막 없이 보기",
    source: "콘텐츠 소비 트렌드 예문",
    full_translation:
      "요즘, 일본 애니메이션이나 음악을 좋아해서, 자막 없이 보고 싶다고 생각하는 사람이 늘고 있습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "最近、",
        reading: "사이킨,",
        definition: "요즘,",
        pos: "부사",
        meta: { word: "最近", readingRoot: "사이킨" },
      },
      {
        token_id: 2,
        surface: "日本の",
        reading: "니혼노",
        definition: "일본의",
        pos: "명사+조사",
        meta: { word: "日本", particle: "の", readingRoot: "니혼" },
      },
      {
        token_id: 3,
        surface: "アニメや",
        reading: "아니메야",
        definition: "애니메이션이나",
        pos: "명사+조사",
        meta: { word: "アニメ", particle: "や", readingRoot: "아니메" },
      },
      {
        token_id: 4,
        surface: "音楽が",
        reading: "온가쿠가",
        definition: "음악이",
        pos: "명사+조사",
        meta: { word: "音楽", particle: "が", readingRoot: "온가쿠" },
      },
      {
        token_id: 5,
        surface: "好きで、",
        reading: "스키데,",
        definition: "좋아해서,",
        pos: "형용동사(연용형)",
        meta: { word: "好きだ", root: "好き", readingRoot: "스키" },
      },
      {
        token_id: 6,
        surface: "字幕なしで",
        reading: "지마쿠나시데",
        definition: "자막 없이",
        pos: "명사+조사",
        meta: { word: "字幕なし", particle: "で", readingRoot: "지마쿠나시" },
      },
      {
        token_id: 7,
        surface: "見たいと",
        reading: "미타이토",
        definition: "보고 싶다고",
        pos: "동사(희망형)+조사",
        meta: { word: "見たい", particle: "と", readingRoot: "미타이" },
      },
      {
        token_id: 8,
        surface: "思う",
        reading: "오모우",
        definition: "생각하는",
        pos: "동사(연체형)",
        meta: { word: "思う", readingRoot: "오모우" },
      },
      {
        token_id: 9,
        surface: "人が",
        reading: "히토가",
        definition: "사람이",
        pos: "명사+조사",
        meta: { word: "人", particle: "が", readingRoot: "히토" },
      },
      {
        token_id: 10,
        surface: "増えています。",
        reading: "후에테이마스.",
        definition: "늘고 있습니다.",
        pos: "동사(현재진행형)",
        meta: { word: "増える", root: "増え", readingRoot: "후에" },
      },
    ],
  },
  {
    id: "onsen-hot-spring-trip",
    title: "겨울 온천 여행",
    source: "겨울철 온천 여행 예문",
    full_translation:
      "겨울이 되면 눈이 많이 내리는 지방의 온천에 가서, 따뜻한 물에 몸을 담그면서 아름다운 설경을 바라보는 것이 가장 큰 즐거움 중 하나입니다.",
    tokens: [
      {
        token_id: 1,
        surface: "冬になると",
        reading: "후유니나루토",
        definition: "겨울이 되면",
        pos: "명사+동사(조건형)",
        meta: { word: "冬", particle: "になると", readingRoot: "후유" },
      },
      {
        token_id: 2,
        surface: "雪が",
        reading: "유키가",
        definition: "눈이",
        pos: "명사+조사",
        meta: { word: "雪", particle: "が", readingRoot: "유키" },
      },
      {
        token_id: 3,
        surface: "たくさん",
        reading: "타쿠상",
        definition: "많이",
        pos: "부사",
        meta: { word: "たくさん", readingRoot: "타쿠상" },
      },
      {
        token_id: 4,
        surface: "降る",
        reading: "후루",
        definition: "내리는",
        pos: "동사(연체형)",
        meta: { word: "降る", readingRoot: "후루" },
      },
      {
        token_id: 5,
        surface: "地方の",
        reading: "치호오노",
        definition: "지방의",
        pos: "명사+조사",
        meta: { word: "地方", particle: "の", readingRoot: "치호오" },
      },
      {
        token_id: 6,
        surface: "温泉に",
        reading: "온센니",
        definition: "온천에",
        pos: "명사+조사",
        meta: { word: "温泉", particle: "に", readingRoot: "온센" },
      },
      {
        token_id: 7,
        surface: "行って、",
        reading: "잇테,",
        definition: "가서,",
        pos: "동사(연용형)",
        meta: { word: "行く", root: "行っ", readingRoot: "잇" },
      },
      {
        token_id: 8,
        surface: "温かい",
        reading: "아타타카이",
        definition: "따뜻한",
        pos: "형용사(연체형)",
        meta: { word: "温かい", readingRoot: "아타타카이" },
      },
      {
        token_id: 9,
        surface: "お湯に",
        reading: "오유니",
        definition: "물에",
        pos: "명사+조사",
        meta: { word: "お湯", particle: "に", readingRoot: "오유" },
      },
      {
        token_id: 10,
        surface: "体を",
        reading: "카라다오",
        definition: "몸을",
        pos: "명사+조사",
        meta: { word: "体", particle: "を", readingRoot: "카라다" },
      },
      {
        token_id: 11,
        surface: "つけながら",
        reading: "츠케나가라",
        definition: "담그면서",
        pos: "동사(연용형)+접속조사",
        meta: { word: "つける", root: "つけ", particle: "ながら", readingRoot: "츠케" },
      },
      {
        token_id: 12,
        surface: "美しい",
        reading: "우츠쿠시이",
        definition: "아름다운",
        pos: "형용사(연체형)",
        meta: { word: "美しい", readingRoot: "우츠쿠시이" },
      },
      {
        token_id: 13,
        surface: "雪景色を",
        reading: "유키게시키오",
        definition: "설경을",
        pos: "명사+조사",
        meta: { word: "雪景色", particle: "を", readingRoot: "유키게시키" },
      },
      {
        token_id: 14,
        surface: "眺めることが",
        reading: "나가메루코토가",
        definition: "바라보는 것이",
        pos: "동사+형식명사+조사",
        meta: { word: "眺める", particle: "こと+が", readingRoot: "나가메루" },
      },
      {
        token_id: 15,
        surface: "一番の",
        reading: "이치반노",
        definition: "가장 큰",
        pos: "명사+조사",
        meta: { word: "一番", particle: "の", readingRoot: "이치반" },
      },
      {
        token_id: 16,
        surface: "楽しみの",
        reading: "타노시미노",
        definition: "즐거움의",
        pos: "명사+조사",
        meta: { word: "楽しみ", particle: "の", readingRoot: "타노시미" },
      },
      {
        token_id: 17,
        surface: "一つです。",
        reading: "히토츠데스.",
        definition: "하나입니다.",
        pos: "명사+です",
        meta: { word: "一つ", particle: "です", readingRoot: "히토츠" },
      },
    ],
  },
  {
    id: "sakura-hanami",
    title: "봄철 벚꽃놀이",
    source: "봄 벚꽃놀이 예문",
    full_translation:
      "4월이 되면 공원의 벚꽃이 만개하기 때문에, 친구와 함께 도시락을 가지고 꽃구경을 가서, 벚꽃나무 아래에서 느긋하게 시간을 보내는 것이 매년의 습관이 되어 있습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "四月になると",
        reading: "시가츠니나루토",
        definition: "4월이 되면",
        pos: "명사+동사(조건형)",
        meta: { word: "四月", particle: "になると", readingRoot: "시가츠" },
      },
      {
        token_id: 2,
        surface: "公園の",
        reading: "코오엔노",
        definition: "공원의",
        pos: "명사+조사",
        meta: { word: "公園", particle: "の", readingRoot: "코오엔" },
      },
      {
        token_id: 3,
        surface: "桜が",
        reading: "사쿠라가",
        definition: "벚꽃이",
        pos: "명사+조사",
        meta: { word: "桜", particle: "が", readingRoot: "사쿠라" },
      },
      {
        token_id: 4,
        surface: "満開になるので、",
        reading: "망카이니나루노데,",
        definition: "만개하기 때문에,",
        pos: "명사+동사+접속조사",
        meta: { word: "満開", particle: "になるので", readingRoot: "망카이" },
      },
      {
        token_id: 5,
        surface: "友達と",
        reading: "토모다치토",
        definition: "친구와",
        pos: "명사+조사",
        meta: { word: "友達", particle: "と", readingRoot: "토모다치" },
      },
      {
        token_id: 6,
        surface: "一緒に",
        reading: "잇쇼니",
        definition: "함께",
        pos: "부사",
        meta: { word: "一緒に", readingRoot: "잇쇼니" },
      },
      {
        token_id: 7,
        surface: "お弁当を",
        reading: "오벤토오오",
        definition: "도시락을",
        pos: "명사+조사",
        meta: { word: "お弁当", particle: "を", readingRoot: "오벤토오" },
      },
      {
        token_id: 8,
        surface: "持って",
        reading: "못테",
        definition: "가지고",
        pos: "동사(연용형)",
        meta: { word: "持つ", root: "持っ", readingRoot: "못" },
      },
      {
        token_id: 9,
        surface: "花見に",
        reading: "하나미니",
        definition: "꽃구경에",
        pos: "명사+조사",
        meta: { word: "花見", particle: "に", readingRoot: "하나미" },
      },
      {
        token_id: 10,
        surface: "行き、",
        reading: "이키,",
        definition: "가서,",
        pos: "동사(연용형)",
        meta: { word: "行く", root: "行き", readingRoot: "이키" },
      },
      {
        token_id: 11,
        surface: "桜の",
        reading: "사쿠라노",
        definition: "벚꽃의",
        pos: "명사+조사",
        meta: { word: "桜", particle: "の", readingRoot: "사쿠라" },
      },
      {
        token_id: 12,
        surface: "木の下で",
        reading: "키노시타데",
        definition: "나무 아래에서",
        pos: "명사+조사",
        meta: { word: "木の下", particle: "で", readingRoot: "키노시타" },
      },
      {
        token_id: 13,
        surface: "ゆっくり",
        reading: "윳쿠리",
        definition: "느긋하게",
        pos: "부사",
        meta: { word: "ゆっくり", readingRoot: "윳쿠리" },
      },
      {
        token_id: 14,
        surface: "過ごすのが",
        reading: "스고스노가",
        definition: "보내는 것이",
        pos: "동사+형식명사+조사",
        meta: { word: "過ごす", particle: "の+が", readingRoot: "스고스" },
      },
      {
        token_id: 15,
        surface: "毎年の",
        reading: "마이토시노",
        definition: "매년의",
        pos: "명사+조사",
        meta: { word: "毎年", particle: "の", readingRoot: "마이토시" },
      },
      {
        token_id: 16,
        surface: "習慣に",
        reading: "슈우칸니",
        definition: "습관이",
        pos: "명사+조사",
        meta: { word: "習慣", particle: "に", readingRoot: "슈우칸" },
      },
      {
        token_id: 17,
        surface: "なっています。",
        reading: "낫테이마스.",
        definition: "되어 있습니다.",
        pos: "동사(현재진행형)",
        meta: { word: "なる", root: "なっ", readingRoot: "낫" },
      },
    ],
  },
  {
    id: "parttime-job-cafe",
    title: "카페 아르바이트 경험",
    source: "대학생 아르바이트 경험 예문",
    full_translation:
      "대학생이 되고 나서, 역 근처에 있는 카페에서 일주일에 세 번 아르바이트를 하고 있는데, 손님과 일본어로 이야기하는 기회가 늘어난 덕분에 회화 실력이 상당히 늘었습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "大学生になってから、",
        reading: "다이가쿠세이니낫테카라,",
        definition: "대학생이 되고 나서,",
        pos: "명사+동사(연용형)+조사",
        meta: { word: "大学生", particle: "になってから", readingRoot: "다이가쿠세이" },
      },
      {
        token_id: 2,
        surface: "駅の",
        reading: "에키노",
        definition: "역의",
        pos: "명사+조사",
        meta: { word: "駅", particle: "の", readingRoot: "에키" },
      },
      {
        token_id: 3,
        surface: "近くにある",
        reading: "치카쿠니아루",
        definition: "근처에 있는",
        pos: "명사+동사(연체형)",
        meta: { word: "近く", particle: "にある", readingRoot: "치카쿠" },
      },
      {
        token_id: 4,
        surface: "カフェで",
        reading: "카훼데",
        definition: "카페에서",
        pos: "명사+조사",
        meta: { word: "カフェ", particle: "で", readingRoot: "카훼" },
      },
      {
        token_id: 5,
        surface: "週に",
        reading: "슈우니",
        definition: "일주일에",
        pos: "명사+조사",
        meta: { word: "週", particle: "に", readingRoot: "슈우" },
      },
      {
        token_id: 6,
        surface: "三回",
        reading: "산카이",
        definition: "세 번",
        pos: "명사",
        meta: { word: "三回", readingRoot: "산카이" },
      },
      {
        token_id: 7,
        surface: "アルバイトを",
        reading: "아루바이토오",
        definition: "아르바이트를",
        pos: "명사+조사",
        meta: { word: "アルバイト", particle: "を", readingRoot: "아루바이토" },
      },
      {
        token_id: 8,
        surface: "していますが、",
        reading: "시테이마스가,",
        definition: "하고 있는데,",
        pos: "동사(현재진행형)+접속조사",
        meta: { word: "する", root: "して", readingRoot: "시테" },
      },
      {
        token_id: 9,
        surface: "お客さんと",
        reading: "오캬쿠상토",
        definition: "손님과",
        pos: "명사+조사",
        meta: { word: "お客さん", particle: "と", readingRoot: "오캬쿠상" },
      },
      {
        token_id: 10,
        surface: "日本語で",
        reading: "니혼고데",
        definition: "일본어로",
        pos: "명사+조사",
        meta: { word: "日本語", particle: "で", readingRoot: "니혼고" },
      },
      {
        token_id: 11,
        surface: "話す",
        reading: "하나스",
        definition: "이야기하는",
        pos: "동사(연체형)",
        meta: { word: "話す", readingRoot: "하나스" },
      },
      {
        token_id: 12,
        surface: "機会が",
        reading: "키카이가",
        definition: "기회가",
        pos: "명사+조사",
        meta: { word: "機会", particle: "が", readingRoot: "키카이" },
      },
      {
        token_id: 13,
        surface: "増えた",
        reading: "후에타",
        definition: "늘어난",
        pos: "동사(과거형)",
        meta: { word: "増える", root: "増え", readingRoot: "후에" },
      },
      {
        token_id: 14,
        surface: "おかげで",
        reading: "오카게데",
        definition: "덕분에",
        pos: "명사+조사",
        meta: { word: "おかげ", particle: "で", readingRoot: "오카게" },
      },
      {
        token_id: 15,
        surface: "会話力が",
        reading: "카이와료쿠가",
        definition: "회화 실력이",
        pos: "명사+조사",
        meta: { word: "会話力", particle: "が", readingRoot: "카이와료쿠" },
      },
      {
        token_id: 16,
        surface: "ずいぶん",
        reading: "즈이분",
        definition: "상당히",
        pos: "부사",
        meta: { word: "ずいぶん", readingRoot: "즈이분" },
      },
      {
        token_id: 17,
        surface: "上達しました。",
        reading: "죠오타츠시마시타.",
        definition: "늘었습니다.",
        pos: "동사(과거형)",
        meta: { word: "上達する", root: "上達し", readingRoot: "죠오타츠시" },
      },
    ],
  },
  {
    id: "earthquake-preparedness",
    title: "지진 대비 습관",
    source: "일본 지진 대비 예문",
    full_translation:
      "일본은 지진이 많은 나라이기 때문에, 만일의 경우를 위해 물이나 음식을 준비해 두는 것뿐만 아니라, 가족과 대피 장소를 확인해 두는 것이 매우 중요하다고 합니다.",
    tokens: [
      {
        token_id: 1,
        surface: "日本は",
        reading: "니혼와",
        definition: "일본은",
        pos: "명사+조사",
        meta: { word: "日本", particle: "は", readingRoot: "니혼" },
      },
      {
        token_id: 2,
        surface: "地震が",
        reading: "지신가",
        definition: "지진이",
        pos: "명사+조사",
        meta: { word: "地震", particle: "が", readingRoot: "지신" },
      },
      {
        token_id: 3,
        surface: "多い",
        reading: "오오이",
        definition: "많은",
        pos: "형용사(연체형)",
        meta: { word: "多い", readingRoot: "오오이" },
      },
      {
        token_id: 4,
        surface: "国なので、",
        reading: "쿠니나노데,",
        definition: "나라이기 때문에,",
        pos: "명사+접속조사",
        meta: { word: "国", particle: "なので", readingRoot: "쿠니" },
      },
      {
        token_id: 5,
        surface: "いざという",
        reading: "이자토이우",
        definition: "만일이라는",
        pos: "연체구",
        meta: { word: "いざという", readingRoot: "이자토이우" },
      },
      {
        token_id: 6,
        surface: "時のために",
        reading: "토키노타메니",
        definition: "때를 위해",
        pos: "명사+조사",
        meta: { word: "時", particle: "のために", readingRoot: "토키" },
      },
      {
        token_id: 7,
        surface: "水や",
        reading: "미즈야",
        definition: "물이나",
        pos: "명사+조사",
        meta: { word: "水", particle: "や", readingRoot: "미즈" },
      },
      {
        token_id: 8,
        surface: "食べ物を",
        reading: "타베모노오",
        definition: "음식을",
        pos: "명사+조사",
        meta: { word: "食べ物", particle: "を", readingRoot: "타베모노" },
      },
      {
        token_id: 9,
        surface: "用意しておく",
        reading: "요오이시테오쿠",
        definition: "준비해 두는",
        pos: "동사(연체형)",
        meta: { word: "用意する", root: "用意し", readingRoot: "요오이시" },
      },
      {
        token_id: 10,
        surface: "だけでなく、",
        reading: "다케데나쿠,",
        definition: "뿐만 아니라,",
        pos: "조사",
        meta: { word: "だけでなく", readingRoot: "다케데나쿠" },
      },
      {
        token_id: 11,
        surface: "家族と",
        reading: "카조쿠토",
        definition: "가족과",
        pos: "명사+조사",
        meta: { word: "家族", particle: "と", readingRoot: "카조쿠" },
      },
      {
        token_id: 12,
        surface: "避難場所を",
        reading: "히난바쇼오",
        definition: "대피 장소를",
        pos: "명사+조사",
        meta: { word: "避難場所", particle: "を", readingRoot: "히난바쇼" },
      },
      {
        token_id: 13,
        surface: "確認しておく",
        reading: "카쿠닌시테오쿠",
        definition: "확인해 두는",
        pos: "동사(연체형)",
        meta: { word: "確認する", root: "確認し", readingRoot: "카쿠닌시" },
      },
      {
        token_id: 14,
        surface: "ことが",
        reading: "코토가",
        definition: "것이",
        pos: "형식명사+조사",
        meta: { word: "こと", particle: "が", readingRoot: "코토" },
      },
      {
        token_id: 15,
        surface: "とても",
        reading: "토테모",
        definition: "매우",
        pos: "부사",
        meta: { word: "とても", readingRoot: "토테모" },
      },
      {
        token_id: 16,
        surface: "大切だと",
        reading: "타이세츠다토",
        definition: "중요하다고",
        pos: "형용동사+조사",
        meta: { word: "大切だ", particle: "と", readingRoot: "타이세츠다" },
      },
      {
        token_id: 17,
        surface: "言われています。",
        reading: "이와레테이마스.",
        definition: "일컬어지고 있습니다.",
        pos: "동사(수동형+현재진행형)",
        meta: { word: "言われる", root: "言われて", readingRoot: "이와레테" },
      },
    ],
  },
  {
    id: "convenience-store-culture",
    title: "편의점 문화",
    source: "일본 편의점 문화 예문",
    full_translation:
      "일본의 편의점은 24시간 열려 있을 뿐만 아니라, 공공요금 납부나 짐 발송 등도 할 수 있기 때문에, 생활의 모든 장면에서 매우 편리하게 이용되고 있습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "日本の",
        reading: "니혼노",
        definition: "일본의",
        pos: "명사+조사",
        meta: { word: "日本", particle: "の", readingRoot: "니혼" },
      },
      {
        token_id: 2,
        surface: "コンビニは",
        reading: "콘비니와",
        definition: "편의점은",
        pos: "명사+조사",
        meta: { word: "コンビニ", particle: "は", readingRoot: "콘비니" },
      },
      {
        token_id: 3,
        surface: "二十四時間",
        reading: "니쥬우요지캉",
        definition: "24시간",
        pos: "명사",
        meta: { word: "二十四時間", readingRoot: "니쥬우요지캉" },
      },
      {
        token_id: 4,
        surface: "開いている",
        reading: "히라이테이루",
        definition: "열려 있는",
        pos: "동사(현재진행형)",
        meta: { word: "開く", root: "開いてい", readingRoot: "히라이테이" },
      },
      {
        token_id: 5,
        surface: "だけでなく、",
        reading: "다케데나쿠,",
        definition: "뿐만 아니라,",
        pos: "조사",
        meta: { word: "だけでなく", readingRoot: "다케데나쿠" },
      },
      {
        token_id: 6,
        surface: "公共料金の",
        reading: "코오쿄오료오킨노",
        definition: "공공요금의",
        pos: "명사+조사",
        meta: { word: "公共料金", particle: "の", readingRoot: "코오쿄오료오킨" },
      },
      {
        token_id: 7,
        surface: "支払いや",
        reading: "시하라이야",
        definition: "납부나",
        pos: "명사+조사",
        meta: { word: "支払い", particle: "や", readingRoot: "시하라이" },
      },
      {
        token_id: 8,
        surface: "荷物の",
        reading: "니모츠노",
        definition: "짐의",
        pos: "명사+조사",
        meta: { word: "荷物", particle: "の", readingRoot: "니모츠" },
      },
      {
        token_id: 9,
        surface: "発送なども",
        reading: "핫소오나도모",
        definition: "발송 등도",
        pos: "명사+조사",
        meta: { word: "発送", particle: "なども", readingRoot: "핫소오" },
      },
      {
        token_id: 10,
        surface: "できるので、",
        reading: "데키루노데,",
        definition: "할 수 있기 때문에,",
        pos: "동사+접속조사",
        meta: { word: "できる", particle: "ので", readingRoot: "데키루" },
      },
      {
        token_id: 11,
        surface: "生活の",
        reading: "세이카츠노",
        definition: "생활의",
        pos: "명사+조사",
        meta: { word: "生活", particle: "の", readingRoot: "세이카츠" },
      },
      {
        token_id: 12,
        surface: "あらゆる",
        reading: "아라유루",
        definition: "모든",
        pos: "연체사",
        meta: { word: "あらゆる", readingRoot: "아라유루" },
      },
      {
        token_id: 13,
        surface: "場面で",
        reading: "바멘데",
        definition: "장면에서",
        pos: "명사+조사",
        meta: { word: "場面", particle: "で", readingRoot: "바멘" },
      },
      {
        token_id: 14,
        surface: "とても",
        reading: "토테모",
        definition: "매우",
        pos: "부사",
        meta: { word: "とても", readingRoot: "토테모" },
      },
      {
        token_id: 15,
        surface: "便利に",
        reading: "벤리니",
        definition: "편리하게",
        pos: "형용동사(연용형)",
        meta: { word: "便利だ", root: "便利に", readingRoot: "벤리니" },
      },
      {
        token_id: 16,
        surface: "利用されています。",
        reading: "리요오사레테이마스.",
        definition: "이용되고 있습니다.",
        pos: "동사(수동형+현재진행형)",
        meta: { word: "利用される", root: "利用され", readingRoot: "리요오사레" },
      },
    ],
  },
  {
    id: "osaka-travel",
    title: "오사카 여행기",
    source: "오사카 여행 후기 예문",
    full_translation:
      "지난달, 오사카에 여행 갔을 때, 도톤보리에서 유명한 다코야키를 먹거나, 많은 사람들로 붐비는 상점가를 걷거나 하면서, 매우 즐거운 시간을 보낼 수 있었습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "先月、",
        reading: "센게츠,",
        definition: "지난달,",
        pos: "명사",
        meta: { word: "先月", readingRoot: "센게츠" },
      },
      {
        token_id: 2,
        surface: "大阪に",
        reading: "오오사카니",
        definition: "오사카에",
        pos: "명사+조사",
        meta: { word: "大阪", particle: "に", readingRoot: "오오사카" },
      },
      {
        token_id: 3,
        surface: "旅行に",
        reading: "료코오니",
        definition: "여행에",
        pos: "명사+조사",
        meta: { word: "旅行", particle: "に", readingRoot: "료코오" },
      },
      {
        token_id: 4,
        surface: "行った",
        reading: "잇타",
        definition: "간",
        pos: "동사(과거형)",
        meta: { word: "行く", root: "行っ", readingRoot: "잇" },
      },
      {
        token_id: 5,
        surface: "時、",
        reading: "토키,",
        definition: "때,",
        pos: "명사",
        meta: { word: "時", readingRoot: "토키" },
      },
      {
        token_id: 6,
        surface: "道頓堀で",
        reading: "도오톤보리데",
        definition: "도톤보리에서",
        pos: "명사+조사",
        meta: { word: "道頓堀", particle: "で", readingRoot: "도오톤보리" },
      },
      {
        token_id: 7,
        surface: "有名な",
        reading: "유우메이나",
        definition: "유명한",
        pos: "형용동사(연체형)",
        meta: { word: "有名だ", root: "有名な", readingRoot: "유우메이나" },
      },
      {
        token_id: 8,
        surface: "たこ焼きを",
        reading: "타코야키오",
        definition: "다코야키를",
        pos: "명사+조사",
        meta: { word: "たこ焼き", particle: "を", readingRoot: "타코야키" },
      },
      {
        token_id: 9,
        surface: "食べたり、",
        reading: "타베타리,",
        definition: "먹거나,",
        pos: "동사(たり형)",
        meta: { word: "食べる", root: "食べたり", readingRoot: "타베타리" },
      },
      {
        token_id: 10,
        surface: "たくさんの",
        reading: "타쿠상노",
        definition: "많은",
        pos: "부사+조사",
        meta: { word: "たくさん", particle: "の", readingRoot: "타쿠상" },
      },
      {
        token_id: 11,
        surface: "人で",
        reading: "히토데",
        definition: "사람으로",
        pos: "명사+조사",
        meta: { word: "人", particle: "で", readingRoot: "히토" },
      },
      {
        token_id: 12,
        surface: "にぎわう",
        reading: "니기와우",
        definition: "붐비는",
        pos: "동사(연체형)",
        meta: { word: "にぎわう", readingRoot: "니기와우" },
      },
      {
        token_id: 13,
        surface: "商店街を",
        reading: "쇼오텐가이오",
        definition: "상점가를",
        pos: "명사+조사",
        meta: { word: "商店街", particle: "を", readingRoot: "쇼오텐가이" },
      },
      {
        token_id: 14,
        surface: "歩いたりして、",
        reading: "아루이타리시테,",
        definition: "걷거나 하면서,",
        pos: "동사(たり형)+동사(연용형)",
        meta: { word: "歩く", root: "歩いたりして", readingRoot: "아루이타리시테" },
      },
      {
        token_id: 15,
        surface: "とても",
        reading: "토테모",
        definition: "매우",
        pos: "부사",
        meta: { word: "とても", readingRoot: "토테모" },
      },
      {
        token_id: 16,
        surface: "楽しい",
        reading: "타노시이",
        definition: "즐거운",
        pos: "형용사(연체형)",
        meta: { word: "楽しい", readingRoot: "타노시이" },
      },
      {
        token_id: 17,
        surface: "時間を",
        reading: "지캉오",
        definition: "시간을",
        pos: "명사+조사",
        meta: { word: "時間", particle: "を", readingRoot: "지캉" },
      },
      {
        token_id: 18,
        surface: "過ごすことが",
        reading: "스고스코토가",
        definition: "보내는 것을",
        pos: "동사+형식명사+조사",
        meta: { word: "過ごす", particle: "こと+が", readingRoot: "스고스" },
      },
      {
        token_id: 19,
        surface: "できました。",
        reading: "데키마시타.",
        definition: "할 수 있었습니다.",
        pos: "동사(과거형)",
        meta: { word: "できる", root: "でき", readingRoot: "데키" },
      },
    ],
  },
  {
    id: "sushi-restaurant-etiquette",
    title: "회전초밥집 이용법",
    source: "회전초밥집 이용 예문",
    full_translation:
      "일본의 회전초밥집에 갔을 때는, 좋아하는 재료를 자유롭게 고를 수 있을 뿐만 아니라, 터치패널로 주문하면 레인을 타고 신선한 초밥이 자리까지 운반되어 오기 때문에, 매우 편리하고 즐겁습니다.",
    tokens: [
      {
        token_id: 1,
        surface: "日本の",
        reading: "니혼노",
        definition: "일본의",
        pos: "명사+조사",
        meta: { word: "日本", particle: "の", readingRoot: "니혼" },
      },
      {
        token_id: 2,
        surface: "回転寿司に",
        reading: "카이텐즈시니",
        definition: "회전초밥집에",
        pos: "명사+조사",
        meta: { word: "回転寿司", particle: "に", readingRoot: "카이텐즈시" },
      },
      {
        token_id: 3,
        surface: "行った",
        reading: "잇타",
        definition: "간",
        pos: "동사(과거형)",
        meta: { word: "行く", root: "行っ", readingRoot: "잇" },
      },
      {
        token_id: 4,
        surface: "時は、",
        reading: "토키와,",
        definition: "때는,",
        pos: "명사+조사",
        meta: { word: "時", particle: "は", readingRoot: "토키" },
      },
      {
        token_id: 5,
        surface: "好きな",
        reading: "스키나",
        definition: "좋아하는",
        pos: "형용동사(연체형)",
        meta: { word: "好きだ", root: "好きな", readingRoot: "스키나" },
      },
      {
        token_id: 6,
        surface: "ネタを",
        reading: "네타오",
        definition: "재료를",
        pos: "명사+조사",
        meta: { word: "ネタ", particle: "を", readingRoot: "네타" },
      },
      {
        token_id: 7,
        surface: "自由に",
        reading: "지유우니",
        definition: "자유롭게",
        pos: "형용동사(연용형)",
        meta: { word: "自由だ", root: "自由に", readingRoot: "지유우니" },
      },
      {
        token_id: 8,
        surface: "選べる",
        reading: "에라베루",
        definition: "고를 수 있는",
        pos: "동사(가능형)",
        meta: { word: "選べる", readingRoot: "에라베루" },
      },
      {
        token_id: 9,
        surface: "だけでなく、",
        reading: "다케데나쿠,",
        definition: "뿐만 아니라,",
        pos: "조사",
        meta: { word: "だけでなく", readingRoot: "다케데나쿠" },
      },
      {
        token_id: 10,
        surface: "タッチパネルで",
        reading: "탓치파네루데",
        definition: "터치패널로",
        pos: "명사+조사",
        meta: { word: "タッチパネル", particle: "で", readingRoot: "탓치파네루" },
      },
      {
        token_id: 11,
        surface: "注文すれば",
        reading: "츄우몬스레바",
        definition: "주문하면",
        pos: "동사(가정형)",
        meta: { word: "注文する", root: "注文すれば", readingRoot: "츄우몬스레바" },
      },
      {
        token_id: 12,
        surface: "レーンに",
        reading: "레엔니",
        definition: "레인에",
        pos: "명사+조사",
        meta: { word: "レーン", particle: "に", readingRoot: "레엔" },
      },
      {
        token_id: 13,
        surface: "乗って",
        reading: "놋테",
        definition: "타고",
        pos: "동사(연용형)",
        meta: { word: "乗る", root: "乗っ", readingRoot: "놋" },
      },
      {
        token_id: 14,
        surface: "新鮮な",
        reading: "신센나",
        definition: "신선한",
        pos: "형용동사(연체형)",
        meta: { word: "新鮮だ", root: "新鮮な", readingRoot: "신센나" },
      },
      {
        token_id: 15,
        surface: "寿司が",
        reading: "스시가",
        definition: "초밥이",
        pos: "명사+조사",
        meta: { word: "寿司", particle: "が", readingRoot: "스시" },
      },
      {
        token_id: 16,
        surface: "席まで",
        reading: "세키마데",
        definition: "자리까지",
        pos: "명사+조사",
        meta: { word: "席", particle: "まで", readingRoot: "세키" },
      },
      {
        token_id: 17,
        surface: "運ばれてくるので、",
        reading: "하코바레테쿠루노데,",
        definition: "운반되어 오기 때문에,",
        pos: "동사(수동형)+접속조사",
        meta: { word: "運ばれる", root: "運ばれてくる", readingRoot: "하코바레테쿠루" },
      },
      {
        token_id: 18,
        surface: "とても",
        reading: "토테모",
        definition: "매우",
        pos: "부사",
        meta: { word: "とても", readingRoot: "토테모" },
      },
      {
        token_id: 19,
        surface: "便利で",
        reading: "벤리데",
        definition: "편리하고",
        pos: "형용동사(연용형)",
        meta: { word: "便利だ", root: "便利で", readingRoot: "벤리데" },
      },
      {
        token_id: 20,
        surface: "楽しいです。",
        reading: "타노시이데스.",
        definition: "즐겁습니다.",
        pos: "형용사+です",
        meta: { word: "楽しい", particle: "です", readingRoot: "타노시이" },
      },
    ],
  },
];

export function getContentById(id: string): Content | undefined {
  return contents.find((c) => c.id === id);
}
